data_settings:
    dataset_path: 'tokenized_data_subword_v2'
    vocabulary_path: 'tokenized_data_subword_v2/vocabulary.pickle'
    special_tokens: ['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]']
seq2seq_params:
    model_name: 'transformer'
    encoder_embedding_dim: 512
    decoder_embedding_dim: 512
    hidden_dim: 512
    num_layers: 6
    dropout: 0.3
train:
    epochs: 10
    batch_size: 2
    learning_rate: 0.00001
    checkpoint_folder: 'checkpoints'
    load_checkpoint : False
infer:
    batch_size: 1
    checkpoint_folder: 'checkpoints'
    load_checkpoint : True
